// src/components/LanguageToggle.tsx
import { Link } from "react-router-dom";

type LanguageToggleProps = {
  to: string;
  label: string;
  langToSave: "en" | "ru";
};

export default function LanguageToggle({ to, label, langToSave }: LanguageToggleProps) {
  return (
    <Link
      to={to}
      className="control-btn"
      onClick={() => window.localStorage.setItem("preferred-language", langToSave)}
    >
      {label}
    </Link>
  );
}

// src/components/LanguageToggle.vue
<script setup lang="ts">
import { RouterLink } from "vue-router";

defineProps<{
  to: string;
  label: string;
  langToSave: "en" | "ru";
}>();

function persistLanguage(langToSave: "en" | "ru") {
  window.localStorage.setItem("preferred-language", langToSave);
}
</script>

<template>
  <RouterLink :to="to" class="control-btn" @click="persistLanguage(langToSave)">
    {{ label }}
  </RouterLink>
</template>
