// src/components/now-playing-bar.tsx
import { For, Show, createEffect, createMemo, createSignal, onCleanup, onMount } from 'solid-js'
import {
  ListMusic, Pause, Play, Repeat, Repeat1, Shuffle,
  SkipBack, SkipForward, Volume2, VolumeX, X,
} from 'lucide-solid'
import { usePlayer } from '@/features/player/usePlayer'

function clamp01(value: number): number {
  return Math.max(0, Math.min(1, value))
}

function fmtTime(seconds: number | null): string {
  if (typeof seconds !== 'number' || !Number.isFinite(seconds) || seconds < 0) return '--:--'
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}:${String(s).padStart(2, '0')}`
}

function ratioFromPointer(event: PointerEvent, target: HTMLElement): number {
  const rect = target.getBoundingClientRect()
  if (rect.width <= 0) return 0
  return (event.clientX - rect.left) / rect.width
}

export function NowPlayingBar(props: { isMusicRoute: boolean; lang?: string }) {
  const player = usePlayer()
  const [nextUpOpen, setNextUpOpen] = createSignal(false)
  const [fullscreenOpen, setFullscreenOpen] = createSignal(false)
  const [volumeOpen, setVolumeOpen] = createSignal(false)
  const [seekDragRatio, setSeekDragRatio] = createSignal<number | null>(null)
  let panelRef: HTMLDivElement | undefined
  let nextUpButtonRef: HTMLButtonElement | undefined
  let volumeBoxRef: HTMLDivElement | undefined
  let volumeCloseTimer: number | null = null

  const shouldShow = createMemo(() => Boolean(player.state.queue && player.currentTrack() && (props.isMusicRoute || player.state.hasStartedPlayback)))
  const progress = createMemo(() => {
    if (player.state.duration <= 0) return 0
    return Math.max(0, Math.min(100, (player.state.currentTime / player.state.duration) * 100))
  })
  const buffered = createMemo(() => {
    if (player.state.duration <= 0) return 0
    const value = (player.state.bufferedTime / player.state.duration) * 100
    return Math.max(0, Math.min(100, value))
  })
  const displayProgress = createMemo(() => {
    const drag = seekDragRatio()
    if (drag == null) return progress()
    return Math.max(0, Math.min(100, drag * 100))
  })
  const displayCurrentTime = createMemo(() => {
    const drag = seekDragRatio()
    if (drag == null) return fmtTime(player.state.currentTime)
    return fmtTime(player.state.duration * drag)
  })
  const currentQueueTracks = createMemo(() => player.state.queue?.tracks ?? [])
  const repeatLabel = createMemo(() => {
    if (player.state.repeatMode === 'one') return 'Repeat One'
    if (player.state.repeatMode === 'all') return 'Repeat All'
    return 'Repeat Off'
  })

  function clearVolumeCloseTimer() {
    if (volumeCloseTimer === null) return
    window.clearTimeout(volumeCloseTimer)
    volumeCloseTimer = null
  }

  function openVolumePopup() {
    clearVolumeCloseTimer()
    setVolumeOpen(true)
  }

  function scheduleVolumePopupClose() {
    clearVolumeCloseTimer()
    volumeCloseTimer = window.setTimeout(() => {
      setVolumeOpen(false)
      volumeCloseTimer = null
    }, 180)
  }

  function onVolumeFocusOut(event: FocusEvent) {
    const nextTarget = event.relatedTarget as Node | null
    if (nextTarget && volumeBoxRef?.contains(nextTarget)) return
    scheduleVolumePopupClose()
  }

  function onSeekPointerDown(event: PointerEvent) {
    if (player.state.duration <= 0) return
    if (typeof event.button === 'number' && event.button !== 0) return
    const target = event.currentTarget as HTMLElement
    try { target.setPointerCapture(event.pointerId) } catch { }
    const ratio = clamp01(ratioFromPointer(event, target))
    setSeekDragRatio(ratio)
    player.seekByRatio(ratio)
  }

  function onSeekPointerMove(event: PointerEvent) {
    const current = seekDragRatio()
    if (current == null) return
    const target = event.currentTarget as HTMLElement
    const ratio = clamp01(ratioFromPointer(event, target))
    setSeekDragRatio(ratio)
    player.seekByRatio(ratio)
  }

  function onSeekPointerUp(event: PointerEvent) {
    const current = seekDragRatio()
    if (current == null) return
    const target = event.currentTarget as HTMLElement
    try { target.releasePointerCapture(event.pointerId) } catch { }
    setSeekDragRatio(null)
  }

  function onPointerDown(event: PointerEvent) {
    if (!nextUpOpen()) return
    const node = event.target as Node | null
    if (!node) return
    if (panelRef?.contains(node)) return
    if (nextUpButtonRef?.contains(node)) return
    setNextUpOpen(false)
  }

  function onBarClick(event: MouseEvent) {
    const target = event.target as HTMLElement | null
    if (!target) return
    if (target.closest('[data-no-fullscreen]')) return
    setFullscreenOpen(true)
  }

  createEffect(() => {
    document.body.classList.toggle('has-now-playing-bar', shouldShow())
    if (!shouldShow()) {
      setFullscreenOpen(false); setNextUpOpen(false); setVolumeOpen(false); clearVolumeCloseTimer()
    }
  })

  createEffect(() => { document.body.classList.toggle('has-now-playing-fullscreen', fullscreenOpen()) })

  onMount(() => { window.addEventListener('pointerdown', onPointerDown) })
  onCleanup(() => {
    document.body.classList.remove('has-now-playing-bar')
    document.body.classList.remove('has-now-playing-fullscreen')
    window.removeEventListener('pointerdown', onPointerDown)
    clearVolumeCloseTimer()
  })

  return (
    <Show when={shouldShow() && player.state.queue && player.currentTrack()}>
      <Show when={nextUpOpen()}>
        <div ref={panelRef} class="now-playing-nextup" role="dialog" aria-label="Next up">
          <div class="now-playing-nextup-head">
            <h4>Next up</h4>
            <button type="button" onClick={() => setNextUpOpen(false)} aria-label="Close next up">
              <X class="now-playing-icon" />
            </button>
          </div>
          <Show when={player.upcomingTracks().length > 0} fallback={<p class="now-playing-nextup-empty">Queue is empty.</p>}>
            <ul>
              <For each={player.upcomingTracks()}>
                {(item) => (
                  <li>
                    <button type="button" onClick={() => player.playTrack(item.index)}>
                      <div class="progressive-cover" style={{ 'background-image': `url(${player.state.queue!.coverUrl})`, width: '36px', height: '36px', 'border-radius': '2px', 'flex-shrink': '0' }}>
                        <img src={player.state.queue!.coverUrl} alt="" width="36" height="36" onLoad={(e) => e.currentTarget.classList.add('loaded')} />
                      </div>
                      <div>
                        <span>{player.state.queue!.artist}</span>
                        <strong>{item.track.title}</strong>
                      </div>
                      <time>{fmtTime(item.duration)}</time>
                    </button>
                  </li>
                )}
              </For>
            </ul>
          </Show>
        </div>
      </Show>

      <Show when={fullscreenOpen()}>
        <div class="now-playing-fullscreen" role="dialog" aria-modal="true" aria-label="Now playing fullscreen">
          <button type="button" class="now-playing-fullscreen-close" aria-label="Close fullscreen player" onClick={() => setFullscreenOpen(false)}>
            <X class="now-playing-icon" />
          </button>
          <div class="now-playing-fullscreen-shell">
            <section class="now-playing-fullscreen-hero">
              <div class="now-playing-fullscreen-art-card">
                <div class="now-playing-fullscreen-art">
                  <div class="progressive-cover" style={{ 'background-image': `url(${player.state.queue!.coverUrl})` }}>
                    <img src={player.state.queue!.coverUrl} alt={`${player.state.queue!.albumTitle} cover`} width="320" height="320" onLoad={(e) => e.currentTarget.classList.add('loaded')} />
                  </div>
                </div>
                <div class="now-playing-fullscreen-meta">
                  <div class="now-playing-fullscreen-artist">{player.state.queue!.artist}</div>
                  <h2>{player.currentTrack()!.title}</h2>
                  <p>{player.state.queue!.albumTitle}</p>
                </div>
              </div>
            </section>
            <section class="now-playing-fullscreen-panel">
              <div class="now-playing-fullscreen-toolbar">
                <div class="now-playing-fullscreen-modes">
                  <button type="button" class={`now-playing-btn now-playing-btn-small${player.state.shuffleEnabled ? ' is-active' : ''}`} aria-label="Shuffle" onClick={player.toggleShuffle}>
                    <Shuffle class="now-playing-icon" />
                  </button>
                  <button type="button" class={`now-playing-btn now-playing-btn-small${player.state.repeatMode !== 'off' ? ' is-active' : ''}`} aria-label={repeatLabel()} onClick={player.cycleRepeatMode}>
                    <Show when={player.state.repeatMode === 'one'} fallback={<Repeat class="now-playing-icon" />}>
                      <Repeat1 class="now-playing-icon" />
                    </Show>
                  </button>
                </div>
              </div>
              <div class="now-playing-fullscreen-playback">
                <div class="now-playing-fullscreen-progress">
                  <div class="now-playing-time">{displayCurrentTime()}</div>
                  <div
                    class={`now-playing-progress${seekDragRatio() !== null ? ' is-dragging' : ''}`}
                    role="slider"
                    aria-valuemin={0}
                    aria-valuemax={Math.max(player.state.duration, 1)}
                    aria-valuenow={seekDragRatio() == null ? player.state.currentTime : player.state.duration * seekDragRatio()!}
                    aria-label="Playback position"
                    onPointerDown={onSeekPointerDown}
                    onPointerMove={onSeekPointerMove}
                    onPointerUp={onSeekPointerUp}
                    onPointerCancel={onSeekPointerUp}
                  >
                    <span class="now-playing-progress-buffer" style={{ width: `${buffered()}%` }} />
                    <span class="now-playing-progress-fill" style={{ width: `${displayProgress()}%` }} />
                    <span class="now-playing-progress-knob" style={{ left: `${displayProgress()}%` }} />
                  </div>
                  <div class="now-playing-time">{fmtTime(player.state.duration)}</div>
                </div>
                <div class="now-playing-fullscreen-controls">
                  <button type="button" class="now-playing-btn" aria-label="Previous track" onClick={player.prevTrack}><SkipBack class="now-playing-icon" /></button>
                  <button type="button" class="now-playing-btn now-playing-btn-main" aria-label={player.state.playing ? 'Pause' : 'Play'} onClick={player.togglePlayPause}>
                    <Show when={player.state.playing} fallback={<Play class="now-playing-icon now-playing-icon-play" />}>
                      <Pause class="now-playing-icon now-playing-icon-pause" />
                    </Show>
                  </button>
                  <button type="button" class="now-playing-btn" aria-label="Next track" onClick={player.nextTrack}><SkipForward class="now-playing-icon" /></button>
                </div>
              </div>
              <div class="now-playing-fullscreen-tracklist">
                <div class="now-playing-fullscreen-tracklist-head">Tracklist</div>
                <ul>
                  <For each={currentQueueTracks()}>
                    {(track, index) => (
                      <li class={index() === player.state.currentIndex ? 'is-active' : ''}>
                        <button type="button" onClick={() => player.playTrack(index())}>
                          <span class="now-playing-fullscreen-track-index">{index() + 1}</span>
                          <span class="now-playing-fullscreen-track-title">{track.title}</span>
                          <span class="now-playing-fullscreen-track-time">{fmtTime(track.duration ?? null)}</span>
                        </button>
                      </li>
                    )}
                  </For>
                </ul>
              </div>
            </section>
          </div>
        </div>
      </Show>

      <div class="now-playing-bar" role="region" aria-label="Now playing" onClick={onBarClick}>
        <div class="now-playing-bar-inner">
          <div class="now-playing-controls" data-no-fullscreen>
            <button type="button" class="now-playing-btn" aria-label="Previous track" onClick={(e) => { e.stopPropagation(); player.prevTrack() }}><SkipBack class="now-playing-icon" /></button>
            <button type="button" class="now-playing-btn now-playing-btn-main" aria-label={player.state.playing ? 'Pause' : 'Play'} onClick={(e) => { e.stopPropagation(); player.togglePlayPause() }}>
              <Show when={player.state.playing} fallback={<Play class="now-playing-icon now-playing-icon-play" />}>
                <Pause class="now-playing-icon now-playing-icon-pause" />
              </Show>
            </button>
            <button type="button" class="now-playing-btn" aria-label="Next track" onClick={(e) => { e.stopPropagation(); player.nextTrack() }}><SkipForward class="now-playing-icon" /></button>
            <button type="button" class={`now-playing-btn now-playing-btn-small${player.state.shuffleEnabled ? ' is-active' : ''}`} aria-label="Shuffle" onClick={(e) => { e.stopPropagation(); player.toggleShuffle() }}><Shuffle class="now-playing-icon" /></button>
            <button type="button" class={`now-playing-btn now-playing-btn-small${player.state.repeatMode !== 'off' ? ' is-active' : ''}`} aria-label="Repeat" onClick={(e) => { e.stopPropagation(); player.cycleRepeatMode() }}>
              <Show when={player.state.repeatMode === 'one'} fallback={<Repeat class="now-playing-icon" />}>
                <Repeat1 class="now-playing-icon" />
              </Show>
            </button>
          </div>
          <div class="now-playing-info">
            <div class="progressive-cover now-playing-cover" style={{ 'background-image': `url(${player.state.queue!.coverUrl})` }}>
              <img src={player.state.queue!.coverUrl} alt="" width="28" height="28" onLoad={(e) => e.currentTarget.classList.add('loaded')} />
            </div>
            <div class="now-playing-meta">
              <div class="now-playing-title">{player.currentTrack()!.title}</div>
              <div class="now-playing-artist">{player.state.queue!.artist}</div>
            </div>
          </div>
          <div class="now-playing-seek" data-no-fullscreen onClick={(e) => e.stopPropagation()}>
            <div class="now-playing-seek-bar"
              role="slider"
              aria-valuemin={0}
              aria-valuemax={Math.max(player.state.duration, 1)}
              aria-valuenow={seekDragRatio() == null ? player.state.currentTime : player.state.duration * seekDragRatio()!}
              aria-label="Playback position"
              onPointerDown={onSeekPointerDown}
              onPointerMove={onSeekPointerMove}
              onPointerUp={onSeekPointerUp}
              onPointerCancel={onSeekPointerUp}
            >
              <span class="now-playing-progress-buffer" style={{ width: `${buffered()}%` }} />
              <span class="now-playing-progress-fill" style={{ width: `${displayProgress()}%` }} />
              <span class="now-playing-progress-knob" style={{ left: `${displayProgress()}%` }} />
            </div>
            <div class="now-playing-seek-time">{displayCurrentTime()}</div>
          </div>
          <div class="now-playing-actions" data-no-fullscreen>
            <div
              ref={volumeBoxRef}
              class={`now-playing-volume-box${volumeOpen() ? ' is-open' : ''}`}
              onClick={(e) => e.stopPropagation()}
              onMouseEnter={openVolumePopup}
              onMouseLeave={scheduleVolumePopupClose}
              onFocusIn={openVolumePopup}
              onFocusOut={onVolumeFocusOut}
            >
              <button type="button" class={`now-playing-btn now-playing-btn-small${player.state.muted || player.state.volume <= 0 ? ' is-muted' : ''}`} aria-label={player.state.muted || player.state.volume <= 0 ? 'Unmute' : 'Mute'} onClick={(e) => { e.stopPropagation(); player.toggleMute() }}>
                <Show when={player.state.muted || player.state.volume <= 0} fallback={<Volume2 class="now-playing-icon" />}>
                  <VolumeX class="now-playing-icon" />
                </Show>
              </button>
              <div class="now-playing-volume-popup">
                <input class="now-playing-volume-slider" type="range" min="0" max="1" step="0.01" value={player.state.muted ? 0 : player.state.volume} aria-label="Volume" onInput={(e) => player.setVolume(Number(e.currentTarget.value))} />
              </div>
            </div>
            <button ref={nextUpButtonRef} type="button" class={`now-playing-btn now-playing-btn-small${nextUpOpen() ? ' is-active' : ''}`} aria-label="Next up" onClick={(e) => { e.stopPropagation(); setNextUpOpen(!nextUpOpen()) }}>
              <ListMusic class="now-playing-icon" />
            </button>
            <button type="button" class="now-playing-btn now-playing-btn-small" aria-label="Close player" onClick={(e) => { e.stopPropagation(); player.clearPlayer() }}>
              <X class="now-playing-icon" />
            </button>
          </div>
        </div>
      </div>
    </Show>
  )
}

// src/components/NowPlayingBar.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import {
  ListMusic,
  Pause,
  Play,
  Repeat,
  Repeat1,
  Shuffle,
  SkipBack,
  SkipForward,
  Volume2,
  VolumeX,
  X
} from "lucide-vue-next";
import { usePlayer } from "@/composables/usePlayer";

const props = defineProps<{
  isMusicRoute: boolean;
  lang: "en" | "ru";
}>();

const {
  state,
  currentTrack,
  upcomingTracks,
  togglePlayPause,
  nextTrack,
  prevTrack,
  seekByRatio,
  setVolume,
  toggleMute,
  toggleShuffle,
  cycleRepeatMode,
  playTrack,
  clearPlayer
} = usePlayer();

const nextUpOpen = ref(false);
const fullscreenOpen = ref(false);
const volumeOpen = ref(false);
const panelRef = ref<HTMLDivElement | null>(null);
const nextUpButtonRef = ref<HTMLButtonElement | null>(null);
const volumeBoxRef = ref<HTMLDivElement | null>(null);
let volumeCloseTimer: number | null = null;

const shouldShow = computed(() => {
  return Boolean(state.queue && currentTrack.value && (props.isMusicRoute || state.hasStartedPlayback));
});

const progress = computed(() => {
  if (state.duration <= 0) return 0;
  return Math.max(0, Math.min(100, (state.currentTime / state.duration) * 100));
});

const buffered = computed(() => {
  if (state.duration <= 0) return 0;
  const value = (state.bufferedTime / state.duration) * 100;
  return Math.max(0, Math.min(100, value));
});

const seekDragRatio = ref<number | null>(null);
const displayProgress = computed(() => {
  if (seekDragRatio.value == null) return progress.value;
  return Math.max(0, Math.min(100, seekDragRatio.value * 100));
});

const displayCurrentTime = computed(() => {
  if (seekDragRatio.value == null) return fmtTime(state.currentTime);
  return fmtTime(state.duration * seekDragRatio.value);
});

const volumeSlider = computed({
  get: () => (state.muted ? 0 : state.volume),
  set: (value: number) => {
    if (!Number.isFinite(value)) return;
    setVolume(value);
  }
});

const currentQueueTracks = computed(() => state.queue?.tracks ?? []);
const repeatLabel = computed(() => {
  if (state.repeatMode === "one") return "Repeat One";
  if (state.repeatMode === "all") return "Repeat All";
  return "Repeat Off";
});

function fmtTime(seconds: number | null): string {
  if (typeof seconds !== "number" || !Number.isFinite(seconds) || seconds < 0) return "--:--";
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

function clamp01(value: number): number {
  return Math.max(0, Math.min(1, value));
}

function ratioFromPointer(event: PointerEvent, target: HTMLElement): number {
  const rect = target.getBoundingClientRect();
  if (rect.width <= 0) return 0;
  return (event.clientX - rect.left) / rect.width;
}

function onSeekPointerDown(event: PointerEvent) {
  if (state.duration <= 0) return;
  if (typeof event.button === "number" && event.button !== 0) return;

  const target = event.currentTarget as HTMLElement;
  try {
    target.setPointerCapture(event.pointerId);
  } catch {
    // ignore
  }

  const ratio = clamp01(ratioFromPointer(event, target));
  seekDragRatio.value = ratio;
  seekByRatio(ratio);
}

function onSeekPointerMove(event: PointerEvent) {
  if (seekDragRatio.value == null) return;
  const target = event.currentTarget as HTMLElement;
  const ratio = clamp01(ratioFromPointer(event, target));
  seekDragRatio.value = ratio;
  seekByRatio(ratio);
}

function onSeekPointerUp(event: PointerEvent) {
  if (seekDragRatio.value == null) return;
  const target = event.currentTarget as HTMLElement;
  try {
    target.releasePointerCapture(event.pointerId);
  } catch {
    // ignore
  }
  seekDragRatio.value = null;
}

function onPointerDown(event: PointerEvent) {
  if (!nextUpOpen.value) return;

  const node = event.target as Node | null;
  if (!node) return;

  if (panelRef.value?.contains(node)) return;
  if (nextUpButtonRef.value?.contains(node)) return;

  nextUpOpen.value = false;
}

function onBarClick(event: MouseEvent) {
  const target = event.target as HTMLElement | null;
  if (!target) return;
  if (target.closest("[data-no-fullscreen]")) {
    return;
  }
  fullscreenOpen.value = true;
}

function clearVolumeCloseTimer() {
  if (volumeCloseTimer === null) return;
  window.clearTimeout(volumeCloseTimer);
  volumeCloseTimer = null;
}

function openVolumePopup() {
  clearVolumeCloseTimer();
  volumeOpen.value = true;
}

function scheduleVolumePopupClose() {
  clearVolumeCloseTimer();
  volumeCloseTimer = window.setTimeout(() => {
    volumeOpen.value = false;
    volumeCloseTimer = null;
  }, 180);
}

function onVolumeFocusOut(event: FocusEvent) {
  const nextTarget = event.relatedTarget as Node | null;
  if (nextTarget && volumeBoxRef.value?.contains(nextTarget)) {
    return;
  }

  scheduleVolumePopupClose();
}

watch(
  shouldShow,
  (value) => {
    document.body.classList.toggle("has-now-playing-bar", value);
    if (!value) {
      fullscreenOpen.value = false;
      nextUpOpen.value = false;
      volumeOpen.value = false;
      clearVolumeCloseTimer();
    }
  },
  { immediate: true }
);

watch(
  fullscreenOpen,
  (value) => {
    document.body.classList.toggle("has-now-playing-fullscreen", value);
  },
  { immediate: true }
);

onMounted(() => {
  window.addEventListener("pointerdown", onPointerDown);
});

onBeforeUnmount(() => {
  document.body.classList.remove("has-now-playing-bar");
  document.body.classList.remove("has-now-playing-fullscreen");
  window.removeEventListener("pointerdown", onPointerDown);
  clearVolumeCloseTimer();
});
</script>

<template>
  <template v-if="shouldShow && state.queue && currentTrack">
    <div v-if="nextUpOpen" ref="panelRef" class="now-playing-nextup" role="dialog" aria-label="Next up">
      <div class="now-playing-nextup-head">
        <h4>Next up</h4>
        <button type="button" @click="nextUpOpen = false" aria-label="Close next up">
          <X class="now-playing-icon" aria-hidden="true" />
        </button>
      </div>

      <p v-if="upcomingTracks.length === 0" class="now-playing-nextup-empty">Queue is empty.</p>

      <ul v-else>
        <li v-for="item in upcomingTracks" :key="`${item.track.url}-${item.index}`">
          <button type="button" @click="playTrack(item.index)">
            <img :src="state.queue.coverUrl" alt="" width="36" height="36" />
            <div>
              <span>{{ state.queue.artist }}</span>
              <strong>{{ item.track.title }}</strong>
            </div>
            <time>{{ fmtTime(item.duration) }}</time>
          </button>
        </li>
      </ul>
    </div>

    <div
      v-if="fullscreenOpen"
      class="now-playing-fullscreen"
      role="dialog"
      aria-modal="true"
      aria-label="Now playing fullscreen"
    >
      <button
        type="button"
        class="now-playing-fullscreen-close"
        aria-label="Close fullscreen player"
        @click="fullscreenOpen = false"
      >
        <X class="now-playing-icon" aria-hidden="true" />
      </button>

      <div class="now-playing-fullscreen-shell">
        <section class="now-playing-fullscreen-hero">
          <div class="now-playing-fullscreen-art-card">
            <div class="now-playing-fullscreen-art">
              <img :src="state.queue.coverUrl" :alt="`${state.queue.albumTitle} cover`" width="320" height="320" />
            </div>

            <div class="now-playing-fullscreen-meta">
              <div class="now-playing-fullscreen-artist">{{ state.queue.artist }}</div>
              <h2>{{ currentTrack.title }}</h2>
              <p>{{ state.queue.albumTitle }}</p>
            </div>
          </div>

          <div class="now-playing-fullscreen-links-card">
            <div class="now-playing-fullscreen-links">
              <a
                v-if="currentTrack.links?.spotify"
                class="stream-badge-image-link"
                :href="currentTrack.links.spotify"
                target="_blank"
                rel="noreferrer"
              >
                <img class="stream-badge-image" src="/media/image/spotify-badge.png?v=20260425-1" alt="Spotify" width="168" height="48" />
              </a>
              <a
                v-if="currentTrack.links?.yandexMusic"
                class="stream-badge-image-link"
                :href="currentTrack.links.yandexMusic"
                target="_blank"
                rel="noreferrer"
              >
                <img class="stream-badge-image" src="/media/image/yandex-badge.png?v=20260425-1" alt="Yandex Music" width="168" height="48" />
              </a>
              <a
                v-if="currentTrack.links?.bandcamp"
                class="stream-badge-image-link"
                :href="currentTrack.links.bandcamp"
                target="_blank"
                rel="noreferrer"
              >
                <img class="stream-badge-image" src="/media/image/bandcamp-badge.png?v=20260425-1" alt="Bandcamp" width="168" height="48" />
              </a>
              <a
                v-if="currentTrack.links?.soundcloud"
                class="stream-badge-image-link"
                :href="currentTrack.links.soundcloud"
                target="_blank"
                rel="noreferrer"
              >
                <img
                  class="stream-badge-image stream-badge-image-soundcloud"
                  src="/media/image/soundcloud-badge.webp?v=20260425-1"
                  alt="SoundCloud"
                  width="168"
                  height="46"
                />
              </a>
            </div>
          </div>
        </section>

        <section class="now-playing-fullscreen-panel">
          <div class="now-playing-fullscreen-toolbar">
            <div class="now-playing-fullscreen-modes">
              <button
                type="button"
                :class="`now-playing-btn now-playing-btn-small${state.shuffleEnabled ? ' is-active' : ''}`"
                aria-label="Shuffle"
                @click="toggleShuffle"
              >
                <Shuffle class="now-playing-icon" aria-hidden="true" />
              </button>
              <button
                type="button"
                :class="`now-playing-btn now-playing-btn-small${state.repeatMode !== 'off' ? ' is-active' : ''}`"
                :aria-label="repeatLabel"
                @click="cycleRepeatMode"
              >
                <Repeat1 v-if="state.repeatMode === 'one'" class="now-playing-icon" aria-hidden="true" />
                <Repeat v-else class="now-playing-icon" aria-hidden="true" />
              </button>
            </div>
          </div>

          <div class="now-playing-fullscreen-playback">
            <div class="now-playing-fullscreen-progress">
              <div class="now-playing-time">{{ displayCurrentTime }}</div>
              <div
                class="now-playing-progress"
                role="slider"
                :class="{ 'is-dragging': seekDragRatio !== null }"
                :aria-valuemin="0"
                :aria-valuemax="Math.max(state.duration, 1)"
                :aria-valuenow="seekDragRatio == null ? state.currentTime : state.duration * seekDragRatio"
                aria-label="Playback position"
                @pointerdown.prevent="onSeekPointerDown"
                @pointermove.prevent="onSeekPointerMove"
                @pointerup.prevent="onSeekPointerUp"
                @pointercancel.prevent="onSeekPointerUp"
              >
                <span class="now-playing-progress-buffer" :style="{ width: `${buffered}%` }" />
                <span class="now-playing-progress-fill" :style="{ width: `${displayProgress}%` }" />
                <span class="now-playing-progress-knob" :style="{ left: `${displayProgress}%` }" />
              </div>
              <div class="now-playing-time">{{ fmtTime(state.duration) }}</div>
            </div>

            <div class="now-playing-fullscreen-controls">
              <button type="button" class="now-playing-btn" aria-label="Previous track" @click="prevTrack">
                <SkipBack class="now-playing-icon" aria-hidden="true" />
              </button>
              <button
                type="button"
                class="now-playing-btn now-playing-btn-main"
                :aria-label="state.playing ? 'Pause' : 'Play'"
                @click="togglePlayPause"
              >
                <Pause v-if="state.playing" class="now-playing-icon now-playing-icon-pause" aria-hidden="true" />
                <Play v-else class="now-playing-icon now-playing-icon-play" aria-hidden="true" />
              </button>
              <button type="button" class="now-playing-btn" aria-label="Next track" @click="nextTrack">
                <SkipForward class="now-playing-icon" aria-hidden="true" />
              </button>
            </div>
          </div>

          <div class="now-playing-fullscreen-tracklist">
            <div class="now-playing-fullscreen-tracklist-head">Tracklist</div>
            <ul>
              <li
                v-for="(track, index) in currentQueueTracks"
                :key="`${track.url}-${index}`"
                :class="{ 'is-active': index === state.currentIndex }"
              >
                <button type="button" @click="playTrack(index)">
                  <span class="now-playing-fullscreen-track-index">{{ index + 1 }}</span>
                  <span class="now-playing-fullscreen-track-title">{{ track.title }}</span>
                  <span class="now-playing-fullscreen-track-time">{{ fmtTime(track.duration ?? null) }}</span>
                </button>
              </li>
            </ul>
          </div>
        </section>
      </div>
    </div>

    <div class="now-playing-bar" role="region" aria-label="Now playing" @click="onBarClick">
      <div class="now-playing-bar-top">
        <div class="now-playing-controls" data-no-fullscreen @click.stop>
          <button type="button" class="now-playing-btn" aria-label="Previous track" @click.stop="prevTrack">
            <SkipBack class="now-playing-icon" aria-hidden="true" />
          </button>
          <button
            type="button"
            class="now-playing-btn now-playing-btn-main"
            :aria-label="state.playing ? 'Pause' : 'Play'"
            @click.stop="togglePlayPause"
          >
            <Pause v-if="state.playing" class="now-playing-icon now-playing-icon-pause" aria-hidden="true" />
            <Play v-else class="now-playing-icon now-playing-icon-play" aria-hidden="true" />
          </button>
          <button type="button" class="now-playing-btn" aria-label="Next track" @click.stop="nextTrack">
            <SkipForward class="now-playing-icon" aria-hidden="true" />
          </button>
          <button
            type="button"
            :class="`now-playing-btn now-playing-btn-small${state.shuffleEnabled ? ' is-active' : ''}`"
            aria-label="Shuffle"
            @click.stop="toggleShuffle"
          >
            <Shuffle class="now-playing-icon" aria-hidden="true" />
          </button>
          <button
            type="button"
            :class="`now-playing-btn now-playing-btn-small${state.repeatMode !== 'off' ? ' is-active' : ''}`"
            aria-label="Repeat"
            @click.stop="cycleRepeatMode"
          >
            <Repeat1 v-if="state.repeatMode === 'one'" class="now-playing-icon" aria-hidden="true" />
            <Repeat v-else class="now-playing-icon" aria-hidden="true" />
          </button>
        </div>

        <div class="now-playing-info">
          <img
            :src="state.queue.coverUrl"
            alt=""
            class="now-playing-cover"
            width="32"
            height="32"
            loading="lazy"
            decoding="async"
          />

          <div class="now-playing-meta">
            <div class="now-playing-title" :title="currentTrack.title">{{ currentTrack.title }}</div>
            <div class="now-playing-artist">{{ state.queue.artist }}</div>
          </div>
        </div>

        <div class="now-playing-actions" data-no-fullscreen @click.stop>
          <div
            ref="volumeBoxRef"
            :class="`now-playing-volume-box${volumeOpen ? ' is-open' : ''}`"
            data-no-fullscreen
            @click.stop
            @mouseenter="openVolumePopup"
            @mouseleave="scheduleVolumePopupClose"
            @focusin="openVolumePopup"
            @focusout="onVolumeFocusOut"
          >
            <button
              type="button"
              :class="`now-playing-btn now-playing-btn-small${state.muted || state.volume <= 0 ? ' is-muted' : ''}`"
              :aria-label="state.muted || state.volume <= 0 ? 'Unmute' : 'Mute'"
              @click.stop="toggleMute"
            >
              <VolumeX v-if="state.muted || state.volume <= 0" class="now-playing-icon" aria-hidden="true" />
              <Volume2 v-else class="now-playing-icon" aria-hidden="true" />
            </button>

            <div class="now-playing-volume-popup">
              <input
                class="now-playing-volume-slider"
                type="range"
                min="0"
                max="1"
                step="0.01"
                v-model.number="volumeSlider"
                aria-label="Volume"
                @click.stop
              />
            </div>
          </div>

          <button
            ref="nextUpButtonRef"
            type="button"
            :class="`now-playing-btn now-playing-btn-small${nextUpOpen ? ' is-active' : ''}`"
            aria-label="Next up"
            data-no-fullscreen
            @click.stop="nextUpOpen = !nextUpOpen"
          >
            <ListMusic class="now-playing-icon" aria-hidden="true" />
          </button>
          <button
            type="button"
            class="now-playing-btn now-playing-btn-small"
            aria-label="Close player"
            data-no-fullscreen
            @click.stop="clearPlayer"
          >
            <X class="now-playing-icon" aria-hidden="true" />
          </button>
        </div>
      </div>

      <div class="now-playing-progress-wrap" data-no-fullscreen @click.stop>
        <div class="now-playing-time">{{ displayCurrentTime }}</div>
        <div
          class="now-playing-progress"
          role="slider"
          :class="{ 'is-dragging': seekDragRatio !== null }"
          :aria-valuemin="0"
          :aria-valuemax="Math.max(state.duration, 1)"
          :aria-valuenow="seekDragRatio == null ? state.currentTime : state.duration * seekDragRatio"
          aria-label="Playback position"
          @pointerdown.prevent="onSeekPointerDown"
          @pointermove.prevent="onSeekPointerMove"
          @pointerup.prevent="onSeekPointerUp"
          @pointercancel.prevent="onSeekPointerUp"
        >
          <span class="now-playing-progress-buffer" :style="{ width: `${buffered}%` }" />
          <span class="now-playing-progress-fill" :style="{ width: `${displayProgress}%` }" />
          <span class="now-playing-progress-knob" :style="{ left: `${displayProgress}%` }" />
        </div>
        <div class="now-playing-time">{{ fmtTime(state.duration) }}</div>
      </div>
    </div>
  </template>
</template>
